service: product-service

frameworkVersion: '2'

provider:
  profile: andery
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  environment:
    PG_HOST: database-2.ca1yha57iyfz.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: postgres
    PG_USERNAME: postgres
    PG_PASSWORD: sqI1YkVdyfX0MqUOfkWX

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  getProductsList:
    handler: handlers/get-products/index.handler
    events:
      - http:
          path: /products
          method: get
  getProductById:
    handler: handlers/get-product-by-id/index.handler
    events:
      - http:
          path: /products/{productId}
          method: get
  createProduct:
    handler: handlers/create-product/index.handler
    events:
      - http:
          path: /products
          method: post