service: product-service

frameworkVersion: '2'

provider:
  profile: andery
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt: [ CatalogItemsQueue, Arn ]
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: CatalogSNSTopic

  environment:
    PG_HOST: database-2.ca1yha57iyfz.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: postgres
    PG_USERNAME: postgres
    PG_PASSWORD: sqI1YkVdyfX0MqUOfkWX
    SNS_ARN:
      Ref: CatalogSNSTopic

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  getProductsList:
    handler: handlers/get-products/index.handler
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductById:
    handler: handlers/get-product-by-id/index.handler
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
  createProduct:
    handler: handlers/create-product/index.handler
    events:
      - http:
          path: /products
          method: post
          cors: true
  catalogBatchProcess:
    handler: handlers/catalog-batch-process/index.handler
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - CatalogItemsQueue
              - Arn

resources:
  Resources:
    CatalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalog-item-queue
    CatalogSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: catalog-sns-topic
    CatalogSNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: anderyaws@gmail.com
        Protocol: email
        TopicArn:
          Ref: CatalogSNSTopic
