openapi: 3.0.0
info:
  title: Swagger MTG API
  description: |
    This is a sample MTG server.
  version: "1.0.0"

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/mtg3/mtg/1.0.0

tags:
  - name: products

paths:
  '/products':
    get:
      tags:
        - products
      summary: Get all products
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Invalid request
  '/products/{productId}':
    get:
      tags:
        - products
      summary: Find product by ID
      description: Returns a single product
      parameters:
        - name: productId
          in: path
          description: ID of product to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Invalid Request

components:
  schemas:
    Product:
      type: object
      required:
        - name
        - id
      properties:
        id:
          type: string
          example: 1669af17-d287-5094-b005-4b143441442f
        name:
          type: string
          example: Abundance